export const CONSTANTS = {
    ARENA_WIDTH: 1132.5,
    ARENA_HEIGHT: 508.5,
    GOAL_WIDTH: 200,
    GOAL_DEPTH: 30,
    PLAYER_OUT_MARGIN: 40,
    POST_RADIUS: 8,
    BALL_RADIUS: 6.4,
    KICK_SPEED: 7,
    BALL_FRICTION: 0.99,
    PLAYER_RADIUS: 17,
    PLAYER_ACCELERATION: 0.20,
    PLAYER_FRICTION: 0.95,
    PLAYER_MAX_SPEED: 4,
    TICK_RATE: 60
};