export const CONSTANTS = {
    TEAM_0_COLOR: 0xd84343,
    TEAM_1_COLOR: 0x2e2be0,
    MAX_PLAYERS: 6,
    ARENA_WIDTH: 1132.5,
    ARENA_HEIGHT: 508.5,
    GOAL_WIDTH: 200,
    GOAL_DEPTH: 30,
    PLAYER_OUT_MARGIN: 40,
    POST_RADIUS: 8,
    MIDDLE_CIRCLE_RADIUS: 100,
    BALL_RADIUS: 6.4,
    KICK_SPEED: 7,
    KICK_COOLDOWN_MILLIS: 900,
    BALL_FRICTION: 0.99,
    PLAYER_RADIUS: 20,
    PLAYER_ACCELERATION: 0.20,
    PLAYER_FRICTION: 0.95,
    PLAYER_MAX_SPEED: 4,
    SPAWN_DISTANCE_RELATIVE: 3 / 5,
    FIELD_PLAYER_SPAWN_ANGLE: 15 * Math.PI / 180,
    ONGOING_JOIN_SPAWN_DISTANCE: - 1 / 20,
    POSSESSION_SECONDS: 10,
    GOAL_CELEBRATION_SECONDS: 3,
    TICK_RATE: 60
};

export const MESSAGES_TYPES = {
    STATE_MESSAGE: "state",
    INPUT_MESSAGE: "input",
    SET_NAME_MESSAGE: "setName",
    RESET_SCORE_MESSAGE: "resetScore",
    GOAL_MESSAGE: "goal",
    TEAMS_MESSAGE: "teams",
    REMOVE_PLAYER_MESSAGE: "input"
};
